dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - ./gradlew clean jar
install:
  - gradle assemble
script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - COVERAGE=$COVERAGE ./gradlew test jacocoTestCoverageVerification
  - echo "Test coverage is "+$COVERAGE
