dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - ./gradlew clean jar
install:
  - gradle assemble
jobs:
  include:
    - env: COVERAGE=0.05 SUT=./monolithic/ui
    - env: COVERAGE=0.05 SUT=./monolithic/service/cart
    - env: COVERAGE=0.05 SUT=./monolithic/service/user
    - env: COVERAGE=0.05 SUT=./monolithic/repository/order
    - env: COVERAGE=0.05 SUT=./monolithic/repository/cart
    - env: COVERAGE=0.05 SUT=./monolithic/repository/product
    - env: COVERAGE=0.05 SUT=./monolithic/repository/user

script:
  - COVERAGE=$COVERAGE ./gradlew $SUT -p check
